base_url = "https://frosted-mug.com"
title = "Council"
description = "Council: a roleplaying game of knowing, choosing, and consequence, by Sir Landis Fishman. The pen is mightier than the die."

compile_sass = false
build_search_index = false
generate_feeds = false
